# Câu 1

# 1/
Gọi C1,C2,C3 lần lượt là cột của ma trận A:
$$
A=
\begin{bmatrix}
1 & 0 & 1\\
0 & 1 & 1\\
1 & 0 & 1\\
0 & 1 & 1
\end{bmatrix}
\in\mathbb{R}^{4\times3}
$$
$$
C1=
\begin{bmatrix}
1\\
0\\
1\\
0
\end{bmatrix}
,
C2=
\begin{bmatrix}
0\\
1\\
0\\
1
\end{bmatrix}
,
C3=
\begin{bmatrix}
1\\
1\\
1\\
1
\end{bmatrix}
$$

Dễ dàng thấy:
$$
C3 -C1=
\begin{bmatrix}
1\\
1\\
1\\
1
\end{bmatrix}
-
\begin{bmatrix}
1\\
0\\
1\\
0
\end{bmatrix}
=
\begin{bmatrix}
0\\
1\\
0\\
1
\end{bmatrix}
=
C2
$$

**=> Các cột của A phụ thuộc tuyến tính**

Hai cột đầu độc lập tuyến tính nên

rank(A)=2
	​


# 2/
$$
A^TA
=
\begin{bmatrix}
2 & 0 & 2 \\
0 & 2 & 2\\
2 & 2 & 4
\end{bmatrix}
$$

In [8]:
import numpy as np
A = [[1,0,1],[0,1,1],[1,0,1],[0,1,1]]
A = np.array(A)
print(A.T@A)

[[2 0 2]
 [0 2 2]
 [2 2 4]]


# 3, 4/ 
Giải phương trình đặc trưng $\det(A^\top A - \lambda I) = 0$:
$$\det \begin{bmatrix} 2-\lambda & 0 & 2 \\ 0 & 2-\lambda & 2 \\ 2 & 2 & 4-\lambda \end{bmatrix} = 0$$
Khai triển định thức:
$$(2-\lambda) \left[(2-\lambda)(4-\lambda) - 4\right] + 2 \left[0 - 2(2-\lambda)\right] = 0$$
$$(2-\lambda) \left[(2-\lambda)(4-\lambda) - 4\right] - 4(2-\lambda) = 0$$
$$\Leftrightarrow (2-\lambda) (\lambda^2 - 6\lambda) = 0 \Leftrightarrow \lambda(2-\lambda)(\lambda - 6) = 0$$
Sắp xếp các trị riêng giảm dần: $\lambda_1 = 6, \quad \lambda_2 = 2, \quad \lambda_3 = 0$.

Tìm các Vector riêng (Eigenvectors) & Trực chuẩn hóa:

Với $\lambda_1 = 6$:

$$
(A^\top A - 6I)v = 0 \iff \begin{bmatrix} -4 & 0 & 2 \\ 0 & -4 & 2 \\ 2 & 2 & -2 \end{bmatrix} \begin{bmatrix} x \\ y \\ z \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix} 
\implies \begin{cases} x = \frac{1}{2}z \\ y = \frac{1}{2}z \end{cases}
$$
Chọn $z = 2 \implies v_1' = \begin{bmatrix} 1 \\ 1 \\ 2 \end{bmatrix}$. Chuẩn hóa vector:
$$
v_1 = \frac{v_1'}{\|v_1'\|} = \frac{1}{\sqrt{6}} \begin{bmatrix} 1 \\ 1 \\ 2 \end{bmatrix}
$$




Với $\lambda_2 = 2$:
$$
(A^\top A - 2I)v = 0 \iff \begin{bmatrix} 0 & 0 & 2 \\ 0 & 0 & 2 \\ 2 & 2 & 2 \end{bmatrix} \begin{bmatrix} x \\ y \\ z \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix}
\implies \begin{cases} z = 0 \\ x = -y \end{cases}
$$
Chọn $y = 1 \implies v_2' = \begin{bmatrix} -1 \\ 1 \\ 0 \end{bmatrix}$. Chuẩn hóa vector:
$$
v_2 = \frac{v_2'}{\|v_2'\|} = \frac{1}{\sqrt{2}} \begin{bmatrix} -1 \\ 1 \\ 0 \end{bmatrix}
$$

Với $\lambda_3 = 0$:
$$
(A^\top A)v = 0 \iff \begin{bmatrix} 2 & 0 & 2 \\ 0 & 2 & 2 \\ 2 & 2 & 4 \end{bmatrix} \begin{bmatrix} x \\ y \\ z \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix}
\implies \begin{cases} x = -z \\ y = -z \end{cases}
$$
Chọn $z = -1 \implies v_3' = \begin{bmatrix} 1 \\ 1 \\ -1 \end{bmatrix}$. Chuẩn hóa vector:
$$
v_3 = \frac{v_3'}{\|v_3'\|} = \frac{1}{\sqrt{3}} \begin{bmatrix} 1 \\ 1 \\ -1 \end{bmatrix}
$$

# 5, 6/
Các giá trị singular value $\sigma_i = \sqrt{\lambda_i}$:
$$
\sigma_1 = \sqrt{6}, \quad \sigma_2 = \sqrt{2}, \quad \sigma_3 = 0
$$
Ma trận Right Singular Vectors $V \in \mathbb{R}^{3 \times 3}$:
$$
V = [v_1 \quad v_2 \quad v_3] = \begin{bmatrix} 
\frac{1}{\sqrt{6}} & -\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{3}} \\[6pt]
\frac{1}{\sqrt{6}} & \frac{1}{\sqrt{2}} & \frac{1}{\sqrt{3}} \\[6pt]
\frac{2}{\sqrt{6}} & 0 & -\frac{1}{\sqrt{3}}
\end{bmatrix}
$$

# 7/

Với $\sigma_1 = \sqrt{6}$:
$$
u_1 = \frac{1}{\sqrt{6}} A v_1 = \frac{1}{\sqrt{6}} \begin{bmatrix} 1 & 0 & 1 \\ 0 & 1 & 1 \\ 1 & 0 & 1 \\ 0 & 1 & 1 \end{bmatrix} \begin{bmatrix} \frac{1}{\sqrt{6}} \\[3pt] \frac{1}{\sqrt{6}} \\[3pt] \frac{2}{\sqrt{6}} \end{bmatrix} 
= \frac{1}{6} \begin{bmatrix} 3 \\ 3 \\ 3 \\ 3 \end{bmatrix} = \begin{bmatrix} 1/2 \\ 1/2 \\ 1/2 \\ 1/2 \end{bmatrix}
$$

Với $\sigma_2 = \sqrt{2}$:
$$
u_2 = \frac{1}{\sqrt{2}} A v_2 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 & 0 & 1 \\ 0 & 1 & 1 \\ 1 & 0 & 1 \\ 0 & 1 & 1 \end{bmatrix} \begin{bmatrix} -\frac{1}{\sqrt{2}} \\[3pt] \frac{1}{\sqrt{2}} \\[3pt] 0 \end{bmatrix} 
= \frac{1}{2} \begin{bmatrix} -1 \\ 1 \\ -1 \\ 1 \end{bmatrix} = \begin{bmatrix} -1/2 \\ 1/2 \\ -1/2 \\ 1/2 \end{bmatrix}
$$

# 8/

Cần tìm $u_3, u_4 \in \mathbb{R}^4$ sao cho $\{u_1, u_2, u_3, u_4\}$ tạo thành một cơ sở trực chuẩn trong $\mathbb{R}^4$.
Điều kiện trực giao $u_3, u_4 \perp \operatorname{span}(u_1, u_2)$:
$$
\begin{cases}
u_1^\top x = 0 \implies x_1 + x_2 + x_3 + x_4 = 0 \\
u_2^\top x = 0 \implies -x_1 + x_2 - x_3 + x_4 = 0
\end{cases}
\iff
\begin{cases}
x_1 + x_3 = 0 \\
x_2 + x_4 = 0
\end{cases}
$$
Chọn 2 vector trực giao và trực chuẩn hóa:
$$
u_3 = \begin{bmatrix} \frac{1}{\sqrt{2}} \\[3pt] 0 \\[3pt] -\frac{1}{\sqrt{2}} \\[3pt] 0 \end{bmatrix}, \quad
u_4 = \begin{bmatrix} 0 \\[3pt] \frac{1}{\sqrt{2}} \\[3pt] 0 \\[3pt] -\frac{1}{\sqrt{2}} \end{bmatrix}
$$

Khai triển **Full SVD** $A = U \Sigma V^\top$:
$$
U = \begin{bmatrix} 
1/2 & -1/2 & 1/\sqrt{2} & 0 \\ 
1/2 & 1/2 & 0 & 1/\sqrt{2} \\ 
1/2 & -1/2 & -1/\sqrt{2} & 0 \\ 
1/2 & 1/2 & 0 & -1/\sqrt{2} 
\end{bmatrix} \in \mathbb{R}^{4 \times 4}
$$
$$
\Sigma = \begin{bmatrix} 
\sqrt{6} & 0 & 0 \\ 
0 & \sqrt{2} & 0 \\ 
0 & 0 & 0 \\ 
0 & 0 & 0 
\end{bmatrix} \in \mathbb{R}^{4 \times 3}
$$
$$
V^\top = \begin{bmatrix} 
\frac{1}{\sqrt{6}} & \frac{1}{\sqrt{6}} & \frac{2}{\sqrt{6}} \\[4pt]
-\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} & 0 \\[4pt]
\frac{1}{\sqrt{3}} & \frac{1}{\sqrt{3}} & -\frac{1}{\sqrt{3}} 
\end{bmatrix} \in \mathbb{R}^{3 \times 3}
$$

In [43]:
U,S,VT = np.linalg.svd(A,full_matrices=True)
print(np.allclose(U.T@U,np.eye(4)))
print(np.allclose(VT@VT.T,np.eye(3)))
Sigma=np.zeros((4,3))
Sigma[:3,:3]=np.diag(S)

print(np.allclose(U@Sigma@VT,A))

True
True
True


# 9,10/

Giữ lại $r = \operatorname{rank}(A) = 2$ thành phần tương ứng với các giá trị $\sigma_i > 0$:
$$
A = U_r \Sigma_r V_r^\top
$$
Kích thước chi tiết các ma trận:

$U_r = \begin{bmatrix} 1/2 & -1/2 \\ 1/2 & 1/2 \\ 1/2 & -1/2 \\ 1/2 & 1/2 \end{bmatrix} \in \mathbb{R}^{4 \times 2}$

$\Sigma_r = \begin{bmatrix} \sqrt{6} & 0 \\ 0 & \sqrt{2} \end{bmatrix} \in \mathbb{R}^{2 \times 2}$

$V_r^\top = \begin{bmatrix} \frac{1}{\sqrt{6}} & \frac{1}{\sqrt{6}} & \frac{2}{\sqrt{6}} \\[4pt] -\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} & 0 \end{bmatrix} \in \mathbb{R}^{2 \times 3}$

# 11/

Do các cột của $U$ và $V$ đều là các hệ vector trực chuẩn thu được từ quá trình trực chuẩn hóa Gram-Schmidt, nên ta luôn có $U^\top U = I_4$ và $V^\top V = I_3$.
Kiểm tra tích $U \Sigma V^\top$:
$$
U \Sigma = \begin{bmatrix} 
\frac{\sqrt{6}}{2} & -\frac{\sqrt{2}}{2} & 0 \\ 
\frac{\sqrt{6}}{2} & \frac{\sqrt{2}}{2} & 0 \\ 
\frac{\sqrt{6}}{2} & -\frac{\sqrt{2}}{2} & 0 \\ 
\frac{\sqrt{6}}{2} & \frac{\sqrt{2}}{2} & 0 
\end{bmatrix}
$$
$$
(U \Sigma) V^\top = \begin{bmatrix} 
\frac{6}{12} + \frac{2}{4} & \frac{6}{12} - \frac{2}{4} & \frac{12}{12} + 0 \\ 
\frac{6}{12} - \frac{2}{4} & \frac{6}{12} + \frac{2}{4} & \frac{12}{12} + 0 \\ 
\frac{6}{12} + \frac{2}{4} & \frac{6}{12} - \frac{2}{4} & \frac{12}{12} + 0 \\ 
\frac{6}{12} - \frac{2}{4} & \frac{6}{12} + \frac{2}{4} & \frac{12}{12} + 0 
\end{bmatrix} = \begin{bmatrix} 1 & 0 & 1 \\ 0 & 1 & 1 \\ 1 & 0 & 1 \\ 0 & 1 & 1 \end{bmatrix} = A
$$

# 12/

**Vì sao có 1 singular value bằng 0?**

Vì $A \in \mathbb{R}^{4 \times 3}$ có $\operatorname{rank}(A) = 2 < 3$, nên chắc chắn có $3 - 2 = 1$ giá trị singular value bằng 0 ($\sigma_3 = 0$).

**Mối liên hệ giữa $v_3$ và Null space của $A$:**

Right singular vector $v_3$ ứng với $\sigma_3 = 0$ chính là một vector cơ sở của $Null(A)$, thỏa mãn $A v_3 = 0$.

**Vì sao Reduced SVD vẫn tái tạo chính xác $A$?**

Reduced SVD chỉ loại bỏ các hàng/cột của $U, \Sigma, V^\top$ ứng với giá trị $\sigma_3 = 0$. Vì các thành phần bị loại bỏ có trọng số bằng 0, tổng các tích ngoài (outer products) cấu thành nên ma trận $A$ không bị thay đổi.


# Câu 2

Ma trận dữ liệu $X$ có các singular values:
$$
\sigma_1 = 12, \quad \sigma_2 = 5, \quad \sigma_3 = 3, \quad \sigma_4 = 1
$$

# 1/

Do ma trận có 4 giá trị singular value đều nghiêm ngặt lớn hơn 0 ($\sigma_i > 0, \forall i = 1..4$), nên:
$$
\operatorname{rank}(X) = 4
$$

# 2/

$$
E_{\text{total}} = \sum_{i=1}^{4} \sigma_i^2 = 12^2 + 5^2 + 3^2 + 1^2 = 144 + 25 + 9 + 1 = 179
$$

# 3,4 /

Tỷ lệ năng lượng giữ lại ứng với hạng $k$:
$$
R(k) = \frac{\sum_{i=1}^{k} \sigma_i^2}{E_{\text{total}}}
$$

$k=1: \quad R(1) = \frac{144}{179} \approx 0.8045 = 80.45\%$

$k=2: \quad R(2) = \frac{144 + 25}{179} = \frac{169}{179} \approx 0.9441 = 94.41\%$

$k=3: \quad R(3) = \frac{169 + 9}{179} = \frac{178}{179} \approx 0.9944 = 99.44\%$

$k=4: \quad R(4) = \frac{179}{179} = 1.0000 = 100.00\%$

| $k$ | Năng lượng giữ lại | Tỷ lệ $R(k)$ |
|---:|---:|---:|
| 1 | 144 | 80.45% |
| 2 | 169 | 94.41% |
| 3 | 178 | 99.44% |
| 4 | 179 | 100.00% |

# 5/

**Ít nhất 80\% năng lượng:** $k = 1$ (đạt $80.45\% \ge 80\%$)

**Ít nhất 90\% năng lượng:** $k = 2$ (đạt $94.41\% \ge 90\%$)

**Ít nhất 95\% năng lượng:** $k = 3$ (đạt $99.44\% \ge 95\%$)

**Ít nhất 99\% năng lượng:** $k = 3$ (đạt $99.44\% \ge 99\%$)

# 6,7/

$$
\|X - X_k\|_F = \sqrt{\sum_{i=k+1}^{4} \sigma_i^2}
$$

$k=1: \quad \|X - X_1\|_F = \sqrt{\sigma_2^2 + \sigma_3^2 + \sigma_4^2} = \sqrt{25 + 9 + 1} = \sqrt{35} \approx 5.916$

$k=2: \quad \|X - X_2\|_F = \sqrt{\sigma_3^2 + \sigma_4^2} = \sqrt{9 + 1} = \sqrt{10} \approx 3.162$

$k=3: \quad \|X - X_3\|_F = \sqrt{\sigma_4^2} = \sqrt{1} = 1.000$

| $k$ | $R(k)$ | $\|X-X_k\|_F$ |
|---:|---:|---:|
| 1 | 80.45% | 5.916 |
| 2 | 94.41% | 3.162 |
| 3 | 99.44% | 1.000 |

# 8/

Khi $\sigma_4 = 1$ đóng vai trò chủ yếu là thành phần nhiễu (noise), ta nên chọn **$k = 3$**.

**Giải thích:** Khi chọn $k = 3$, ta đã giảm số chiều của dữ liệu đi 1 đơn vị và triệt tiêu hoàn toàn thành phần nhiễu đại diện bởi $\sigma_4$. Đồng thời, xấp xỉ $X_3$ vẫn bảo toàn được đến **99.44\%** tổng năng lượng của dữ liệu ban đầu với sai số Frobenius cực kỳ nhỏ ($\|X - X_3\|_F = 1.0$).

# 9/

**Vì sao các singular values phải được sắp xếp giảm dần ($\sigma_1 \ge \sigma_2 \ge \dots$)?**\\
Việc sắp xếp giảm dần giúp đảm bảo rằng các thành phần giữ thông tin quan trọng nhất (biến thiên lớn nhất) luôn được xếp ở đầu. Theo **Định lý Eckart-Young-Mirsky**, việc cắt bỏ các thành phần phía sau với $k$ nhỏ nhất sẽ luôn thu được ma trận xấp xỉ hạng $k$ tối ưu nhất (tối đa hóa năng lượng giữ lại và tối thiểu hóa sai số Frobenius $\|X - X_k\|_F$).

**Giữ càng nhiều singular values có phải lúc nào cũng tốt hơn không?**\\
**Không hẳn.** Giữ lại càng nhiều singular values giúp ma trận khôi phục chính xác hơn nhưng sẽ làm tăng chi phí lưu trữ và thời gian tính toán. Ngoài ra, các singular values nhỏ thường chứa thành phần **nhiễu (noise)** hoặc thông tin dư thừa; việc giữ lại chúng có thể khiến các mô hình học máy bị tình trạng quá khớp (**overfitting**).

**Sự đánh đổi (Trade-off) giữa tỷ lệ năng lượng và mức độ nén dữ liệu:**
**Khi chọn $k$ nhỏ:** Mức độ nén cao (tiết kiệm dung lượng, tốc độ xử lý nhanh, lọc nhiễu tốt) nhưng tỷ lệ năng lượng $R(k)$ thấp, làm tăng sai số và có nguy cơ làm mất các đặc trưng cốt lõi của dữ liệu.
**Khi chọn $k$ lớn:** Tỷ lệ năng lượng $R(k)$ cao (giữ lại hầu như toàn bộ thông tin) nhưng mức độ nén thấp, bộ nhớ lưu trữ lớn và dễ giữ lại cả các thành phần nhiễu không mong muốn.